name = "BesselK"
uuid = "432ab697-7a72-484f-bc4a-bc531f5c819b"
authors = ["Chris Geoga <christopher.geoga@rutgers.edu>"]
version = "0.5.2"

[deps]
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"

[compat]
Polynomials = "2, 3"
julia = "1"
Bessels = "0.2.3"
